MODEL_NAME = "meta-llama/Llama-2-7b-chat-hf" #"google\gemma-2b-it" #"qwen2-7b-chat""
PRODUCTS_FILE = "./data/products.csv"
PERSONAS_FILE = "./data/persona.csv"
PROMPTS_FILE = "./data/prompts.txt"
DIRECTIONS_DIR = "./directions"
METRICS_DIR = "./metrics"
DOMAIN = "Smart Phones"
MAX_NEW_TOKENS = 1000
OUTPUT_DIR = "./outputs"
